Repository SomoimProj/backend, pull requests merged in 2023-04, with the labels that each got.

#53 Feat/46 board modify
  src/main/java/com/oinzo/somoim/controller/BoardController.java
  src/main/java/com/oinzo/somoim/controller/dto/BoardResponse.java
  src/main/java/com/oinzo/somoim/domain/board/repository/ClubBoardRepository.java
  src/main/java/com/oinzo/somoim/domain/board/service/ClubBoardService.java
  src/test/java/com/oinzo/somoim/domain/board/service/BoardControllerTest.java
  src/test/java/com/oinzo/somoim/domain/club/service/ClubControllerTest.java
Labels: 🔨 Refactor

#57 Feat/55 ablum like
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/controller/AlbumLikeController.java
  src/main/java/com/oinzo/somoim/controller/dto/AlbumLikeResponse.java
  src/main/java/com/oinzo/somoim/domain/albumlike/entity/AlbumLike.java
  src/main/java/com/oinzo/somoim/domain/albumlike/repository/AlbumLikeRepository.java
  src/main/java/com/oinzo/somoim/domain/albumlike/service/AlbumLikeService.java
  src/main/java/com/oinzo/somoim/domain/clubuser/repository/ClubUserRepository.java
  src/test/java/com/oinzo/somoim/domain/albumlike/service/AlbumLikeServiceTest.java
Labels: ✨ Feature, ✅ Test

#60 Feat/59 club activity
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/controller/ClubActivityController.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubActivityRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubActivityResponse.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/entity/ClubActivity.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/repository/ClubActivityRepository.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/service/ClubActivityService.java
  src/test/java/com/oinzo/somoim/domain/clubactivity/service/ClubActivityServiceTest.java
Labels: ✨ Feature, ✅ Test

#68 Feat/65 reflect like
  src/main/java/com/oinzo/somoim/controller/ClubAlbumController.java
  src/main/java/com/oinzo/somoim/controller/dto/AlbumResponse.java
  src/main/java/com/oinzo/somoim/controller/dto/BoardResponse.java
  src/main/java/com/oinzo/somoim/domain/album/repository/ClubAlbumRepository.java
  src/main/java/com/oinzo/somoim/domain/album/service/ClubAlbumService.java
  src/main/java/com/oinzo/somoim/domain/albumlike/repository/AlbumLikeRepository.java
  src/main/java/com/oinzo/somoim/domain/board/service/ClubBoardService.java
  src/main/java/com/oinzo/somoim/domain/boardcomment/repository/BoardCommentRepository.java
  src/main/java/com/oinzo/somoim/domain/boardcomment/service/BoardCommentService.java
  src/main/java/com/oinzo/somoim/domain/boardlike/repository/BoardLikeRepository.java
  src/test/java/com/oinzo/somoim/domain/album/service/ClubAlbumServiceTest.java
Labels: 🔨 Refactor

#62 fix: 페이징 정렬 기준에 Id 추가 (#61)
  src/main/java/com/oinzo/somoim/controller/BoardController.java
  src/main/java/com/oinzo/somoim/domain/board/repository/ClubBoardRepository.java
  src/main/java/com/oinzo/somoim/domain/board/service/ClubBoardService.java
  src/main/java/com/oinzo/somoim/domain/club/repository/ClubRepository.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
Labels: 🐞 BugFix

#66 Feat/64 로그아웃 기능
  src/main/java/com/oinzo/somoim/common/jwt/JwtProperties.java
  src/main/java/com/oinzo/somoim/common/response/SuccessResponse.java
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/domain/user/email/EmailService.java
  src/main/java/com/oinzo/somoim/domain/user/service/AuthService.java
Labels: ✨ Feature

#74 fix : Patch시 cors 어노테이션 적용
  src/main/java/com/oinzo/somoim/config/SecurityConfiguration.java
Labels: 🐞 BugFix

#75 fix : 패키지 중복 클래스 삭제
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/domain/user/email/EmailService.java
Labels: 🐞 BugFix

#76 fix : 이메일과 레디스 서비스 추가/수정
  src/main/java/com/oinzo/somoim/common/redis/RedisService.java
  src/main/java/com/oinzo/somoim/domain/user/service/EmailService.java
Labels: 🐞 BugFix

#70 Feat/69 activity user
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/controller/ActivityUserController.java
  src/main/java/com/oinzo/somoim/controller/dto/ActivityUserResponse.java
  src/main/java/com/oinzo/somoim/domain/activityuser/entity/ActivityUser.java
  src/main/java/com/oinzo/somoim/domain/activityuser/repository/ActivityUserRepository.java
  src/main/java/com/oinzo/somoim/domain/activityuser/service/ActivityUserService.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/entity/ClubActivity.java
  src/test/java/com/oinzo/somoim/domain/activityuser/service/ActivityUserServiceTest.java
Labels: ✨ Feature, ✅ Test

#67 Feat/63 토큰 재발급
  src/main/java/com/oinzo/somoim/common/jwt/JwtProvider.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenService.java
  src/main/java/com/oinzo/somoim/common/redis/RedisService.java
  src/main/java/com/oinzo/somoim/config/security/JwtAuthenticationFilter.java
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/domain/user/service/AuthService.java
Labels: ✨ Feature

#79 Feat/77 club modify
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/controller/ClubController.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubDetailResponse.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubResponse.java
  src/main/java/com/oinzo/somoim/domain/club/entity/Club.java
  src/main/java/com/oinzo/somoim/domain/club/repository/ClubRepository.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
Labels: 🔨 Refactor

#78 fix: 클럽 가입멤버 수 직접 카운트하기 (#72)
  src/main/java/com/oinzo/somoim/controller/ClubController.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubDetailResponse.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubResponse.java
  src/main/java/com/oinzo/somoim/domain/board/service/ClubBoardService.java
  src/main/java/com/oinzo/somoim/domain/club/entity/Club.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
  src/main/java/com/oinzo/somoim/domain/clublike/service/ClubLikeService.java
  src/main/java/com/oinzo/somoim/domain/clubuser/entity/ClubUser.java
  src/main/java/com/oinzo/somoim/domain/clubuser/repository/ClubUserRepository.java
  src/main/java/com/oinzo/somoim/domain/clubuser/service/ClubUserService.java
  src/test/java/com/oinzo/somoim/domain/boardcomment/service/BoardCommentServiceTest.java
  src/test/java/com/oinzo/somoim/domain/boardlike/service/BoardLikeServiceTest.java
  src/test/java/com/oinzo/somoim/domain/clublike/service/ClubLikeServiceTest.java
  src/test/java/com/oinzo/somoim/domain/clubuser/service/ClubUserServiceTest.java
Labels: 🐞 BugFix

#83 fix: 관심사에서 비즈니스 삭제 (#82)
  src/main/java/com/oinzo/somoim/common/type/Favorite.java
Labels: 🐞 BugFix

#85 fix: 인증번호 인증 메일의 양식 수정 (#84)
  src/main/java/com/oinzo/somoim/domain/user/service/EmailService.java
Labels: 🐞 BugFix

#87 Feat/63 reissue
  src/main/java/com/oinzo/somoim/common/jwt/JwtProvider.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenDto.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenService.java
  src/main/java/com/oinzo/somoim/config/security/JwtAuthenticationFilter.java
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/controller/OAuth2Controller.java
  src/main/java/com/oinzo/somoim/controller/dto/SignOutRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/TokenResponse.java
  src/main/java/com/oinzo/somoim/domain/user/service/AuthService.java
Labels: 🐞 BugFix

#88 chore : fee 문자열 변경, 액티비티 추가/삭제/수정 시 관리자 검증 진행
  src/main/java/com/oinzo/somoim/controller/dto/ClubActivityRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubActivityResponse.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/entity/ClubActivity.java
  src/main/java/com/oinzo/somoim/domain/clubactivity/service/ClubActivityService.java
  src/test/java/com/oinzo/somoim/domain/clubactivity/service/ClubActivityServiceTest.java
Labels: 🔨 Refactor

#90 fix : 로그아웃 오류 수정
  src/main/java/com/oinzo/somoim/common/jwt/TokenService.java
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/controller/dto/SignOutRequest.java
  src/main/java/com/oinzo/somoim/domain/user/service/AuthService.java
Labels: 🐞 BugFix
