Repository SomoimProj/backend, pull requests merged in 2023-03, with the labels that each got.

#3 Feat/1 jwt
  build.gradle
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/jwt/JwtProperties.java
  src/main/java/com/oinzo/somoim/common/jwt/JwtProvider.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenDto.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenService.java
  src/main/java/com/oinzo/somoim/config/SecurityConfiguration.java
  src/main/java/com/oinzo/somoim/config/security/JwtAccessDeniedHandler.java
  src/main/java/com/oinzo/somoim/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/oinzo/somoim/config/security/JwtAuthenticationFilter.java
  src/main/java/com/oinzo/somoim/config/security/JwtExceptionHandlerFilter.java
  src/main/java/com/oinzo/somoim/config/security/SecurityUser.java
  src/main/java/com/oinzo/somoim/config/security/SecurityUserDetailsService.java
  src/main/java/com/oinzo/somoim/controller/dto/TokenResponse.java
Labels: ✨ Feature

#6 Feat/4 oauth2
  build.gradle
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/config/RestTemplateConfiguration.java
  src/main/java/com/oinzo/somoim/config/SecurityConfiguration.java
  src/main/java/com/oinzo/somoim/controller/OAuth2Controller.java
  src/main/java/com/oinzo/somoim/controller/dto/GoogleLoginRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/kakaoLoginRequest.java
  src/main/java/com/oinzo/somoim/domain/user/dto/GoogleUserInfoDto.java
  src/main/java/com/oinzo/somoim/domain/user/dto/KakaoUserInfoDto.java
  src/main/java/com/oinzo/somoim/domain/user/entity/User.java
  src/main/java/com/oinzo/somoim/domain/user/repository/UserRepository.java
  src/main/java/com/oinzo/somoim/domain/user/service/GoogleOAuth2Service.java
  src/main/java/com/oinzo/somoim/domain/user/service/KakaoOAuth2Service.java
  src/main/java/com/oinzo/somoim/domain/user/service/OAuth2Service.java
Labels: ✨ Feature

#8 Feat/2 club cr
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/type/Favorite.java
  src/main/java/com/oinzo/somoim/domain/club/ClubController.java
  src/main/java/com/oinzo/somoim/domain/club/dto/ClubCreateDto.java
  src/main/java/com/oinzo/somoim/domain/club/dto/ClubRequestDto.java
  src/main/java/com/oinzo/somoim/domain/club/entity/Club.java
  src/main/java/com/oinzo/somoim/domain/club/repository/ClubRepository.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
  src/test/java/com/oinzo/somoim/ClubControllerTest.java
Labels: ✨ Feature

#13 refactor: 코드 리팩토링
  src/main/java/com/oinzo/somoim/common/exception/BaseException.java
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/type/Favorite.java
  src/main/java/com/oinzo/somoim/controller/ClubController.java
  src/main/java/com/oinzo/somoim/controller/dto/ClubRequestDto.java
  src/main/java/com/oinzo/somoim/domain/club/dto/ClubCreateDto.java
  src/main/java/com/oinzo/somoim/domain/club/dto/ClubCreateRequest.java
  src/main/java/com/oinzo/somoim/domain/club/entity/Club.java
  src/main/java/com/oinzo/somoim/domain/club/repository/ClubRepository.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
  src/test/java/com/oinzo/somoim/ClubControllerTest.java
Labels: 🔨 Refactor

#14 Feat/5 email
  build.gradle
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/jwt/JwtProvider.java
  src/main/java/com/oinzo/somoim/common/jwt/TokenDto.java
  src/main/java/com/oinzo/somoim/config/RedisRepositoryConfig.java
  src/main/java/com/oinzo/somoim/config/SecurityConfiguration.java
  src/main/java/com/oinzo/somoim/controller/AuthController.java
  src/main/java/com/oinzo/somoim/controller/dto/TokenResponse.java
  src/main/java/com/oinzo/somoim/domain/user/dto/EmailDto.java
  src/main/java/com/oinzo/somoim/domain/user/dto/SignInDto.java
  src/main/java/com/oinzo/somoim/domain/user/dto/SignUpDto.java
  src/main/java/com/oinzo/somoim/domain/user/email/EmailService.java
  src/main/java/com/oinzo/somoim/domain/user/repository/UserRepository.java
  src/main/java/com/oinzo/somoim/domain/user/service/AuthService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#20 fix: Club 리스트 조회 API에서 지역 받아오는 방식 변경 (#19)
  build.gradle
  src/main/java/com/oinzo/somoim/controller/ClubController.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
  src/test/java/com/oinzo/somoim/ClubControllerTest.java
Labels: 🐞 BugFix

#18 Feat/16 user info
  src/main/java/com/oinzo/somoim/common/annotation/Birth.java
  src/main/java/com/oinzo/somoim/common/annotation/validator/BirthValidator.java
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/exception/ErrorController.java
  src/main/java/com/oinzo/somoim/controller/UserController.java
  src/main/java/com/oinzo/somoim/controller/dto/FavoriteUpdateRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/UserInfoRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/UserInfoResponse.java
  src/main/java/com/oinzo/somoim/domain/user/entity/User.java
  src/main/java/com/oinzo/somoim/domain/user/service/UserService.java
  src/test/java/com/oinzo/somoim/domain/user/service/UserServiceTest.java
Labels: ✨ Feature, ✅ Test

#15 Feat/11 join club
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/type/ClubUserLevel.java
  src/main/java/com/oinzo/somoim/controller/ClubUserController.java
  src/main/java/com/oinzo/somoim/controller/dto/JoinClubRequest.java
  src/main/java/com/oinzo/somoim/domain/club/entity/Club.java
  src/main/java/com/oinzo/somoim/domain/club/service/ClubService.java
  src/main/java/com/oinzo/somoim/domain/clubuser/entity/ClubUser.java
  src/main/java/com/oinzo/somoim/domain/clubuser/repository/ClubUserRepository.java
  src/main/java/com/oinzo/somoim/domain/clubuser/service/ClubUserService.java
  src/main/java/com/oinzo/somoim/domain/user/service/UserService.java
  src/test/java/com/oinzo/somoim/domain/clubuser/service/ClubUserServiceTest.java
  src/test/java/com/oinzo/somoim/domain/user/service/UserServiceTest.java
Labels: ✨ Feature, ✅ Test

#25 Feat/12 board
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/common/type/Category.java
  src/main/java/com/oinzo/somoim/controller/BoardController.java
  src/main/java/com/oinzo/somoim/controller/dto/BoardCreateRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/BoardResponse.java
  src/main/java/com/oinzo/somoim/domain/board/entity/ClubBoard.java
  src/main/java/com/oinzo/somoim/domain/board/repository/ClubBoardRepository.java
  src/main/java/com/oinzo/somoim/domain/board/service/ClubBoardService.java
  src/test/java/com/oinzo/somoim/BoardControllerTest.java
Labels: ✨ Feature

#28 Feat/21 cloudflare
  src/main/java/com/oinzo/somoim/common/service/CloudflareService.java
  src/main/java/com/oinzo/somoim/config/SecurityConfiguration.java
  src/main/java/com/oinzo/somoim/controller/CommonController.java
  src/main/java/com/oinzo/somoim/controller/OAuth2Controller.java
  src/main/java/com/oinzo/somoim/controller/dto/KakaoLoginRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/UploadUrlResponse.java
  src/main/java/com/oinzo/somoim/domain/user/service/GoogleOAuth2Service.java
  src/main/java/com/oinzo/somoim/domain/user/service/KakaoOAuth2Service.java
Labels: ✨ Feature

#31 refactor: 클럽 가입 과정에서 DB 호출 최소화 (#30)
  src/main/java/com/oinzo/somoim/domain/clubuser/entity/ClubUser.java
  src/main/java/com/oinzo/somoim/domain/clubuser/repository/ClubUserRepository.java
  src/main/java/com/oinzo/somoim/domain/clubuser/service/ClubUserService.java
  src/main/java/com/oinzo/somoim/domain/user/service/UserService.java
  src/test/java/com/oinzo/somoim/domain/clubuser/service/ClubUserServiceTest.java
Labels: 🔨 Refactor

#42 fix: 대소문자 상관없이 관심사 매핑하도록 수정 (#41)
  src/main/java/com/oinzo/somoim/common/type/Favorite.java
Labels: 🐞 BugFix

#44 fix: 사용자 관심사를 여러 개 설정 가능하도록 변경 (#43)
  src/main/java/com/oinzo/somoim/controller/UserController.java
  src/main/java/com/oinzo/somoim/controller/dto/FavoriteUpdateRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/UserInfoResponse.java
  src/main/java/com/oinzo/somoim/domain/user/entity/FavoriteListConverter.java
  src/main/java/com/oinzo/somoim/domain/user/entity/User.java
  src/main/java/com/oinzo/somoim/domain/user/service/UserService.java
  src/test/java/com/oinzo/somoim/domain/user/service/UserServiceTest.java
Labels: 🐞 BugFix

#50 fix: 회원정보 조회 API Response에 userId 파라미터 추가 (#49)
  src/main/java/com/oinzo/somoim/controller/dto/UserInfoResponse.java
  src/test/java/com/oinzo/somoim/domain/user/service/UserServiceTest.java
Labels: 🐞 BugFix

#45 Feat/26 album
  src/main/java/com/oinzo/somoim/common/exception/ErrorCode.java
  src/main/java/com/oinzo/somoim/controller/ClubAlbumController.java
  src/main/java/com/oinzo/somoim/controller/dto/AlbumCreateRequest.java
  src/main/java/com/oinzo/somoim/controller/dto/AlbumResponse.java
  src/main/java/com/oinzo/somoim/domain/album/entity/ClubAlbum.java
  src/main/java/com/oinzo/somoim/domain/album/repository/ClubAlbumRepository.java
  src/main/java/com/oinzo/somoim/domain/album/service/ClubAlbumService.java
  src/test/java/com/oinzo/somoim/domain/album/service/ClubAlbumServiceTest.java
Labels: ✨ Feature
